CREATE TABLE IF NOT EXISTS icecream_flavor (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    name_en VARCHAR(50) NOT NULL DEFAULT '',
    description VARCHAR(120) NOT NULL DEFAULT '',
    description_en VARCHAR(120) NOT NULL DEFAULT '',
    is_available BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS order_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flavor_id INTEGER NOT NULL REFERENCES icecream_flavor(id),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    ordered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS error_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES order_history(id) ON DELETE CASCADE,
    process_step VARCHAR(50) NOT NULL
        CHECK (process_step IN (
            'CUP_PICK', 'CUP_PLACE', 'SCOOP_PICK', 'MOVE_TO_ICECREAM',
            'SCOOP_ICECREAM', 'PUT_ICECREAM_IN_CUP', 'SCOOP_RETURN',
            'SPOON_INSERT', 'SERVE_CUP'
        )),
    error_code VARCHAR(50) NOT NULL
        CHECK (error_code IN (
            'GRIP_FAILED', 'MOVE_FAILED', 'SCOOP_FAILED',
            'INSERT_FAILED', 'UNKNOWN_ERROR'
        )),
    message VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_order_history_ordered_at
    ON order_history (ordered_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_history_flavor_id
    ON order_history (flavor_id);
CREATE INDEX IF NOT EXISTS idx_error_log_order_id
    ON error_log (order_id);
CREATE INDEX IF NOT EXISTS idx_error_log_created_at
    ON error_log (created_at DESC);

INSERT INTO icecream_flavor (name, name_en, description, description_en, is_available)
VALUES ('바닐라', 'Vanilla', '부드럽고 진한 기본 바닐라', 'Smooth and rich classic vanilla', TRUE),
       ('초콜릿', 'Chocolate', '초코칩이 씹히는 진한 초콜릿', 'Rich chocolate with crunchy chips', TRUE),
       ('딸기', 'Strawberry', '생딸기 과육이 들어간 상큼함', 'Fresh and fruity strawberry', TRUE),
       ('민트초코', 'Mint Chocolate', '상쾌한 민트와 초콜릿 칩', 'Refreshing mint with chocolate chips', FALSE),
       ('쿠키앤크림', 'Cookies and Cream', '바삭한 쿠키가 가득한 크림', 'Creamy ice cream packed with cookies', FALSE)
ON CONFLICT (name) DO NOTHING;
