CREATE TABLE IF NOT EXISTS icecream_flavor (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    is_available BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS order_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flavor_id INTEGER NOT NULL REFERENCES icecream_flavor(id),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    ordered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS error_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES order_history(id) ON DELETE CASCADE,
    process_step VARCHAR(50) NOT NULL
        CHECK (process_step IN (
            'CUP_PICK', 'CUP_PLACE', 'SCOOP_PICK', 'MOVE_TO_ICECREAM',
            'SCOOP_ICECREAM', 'PUT_ICECREAM_IN_CUP', 'SCOOP_RETURN',
            'SPOON_INSERT', 'SERVE_CUP'
        )),
    error_code VARCHAR(50) NOT NULL
        CHECK (error_code IN (
            'GRIP_FAILED', 'MOVE_FAILED', 'SCOOP_FAILED',
            'INSERT_FAILED', 'UNKNOWN_ERROR'
        )),
    message VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_order_history_ordered_at
    ON order_history (ordered_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_history_flavor_id
    ON order_history (flavor_id);
CREATE INDEX IF NOT EXISTS idx_error_log_order_id
    ON error_log (order_id);
CREATE INDEX IF NOT EXISTS idx_error_log_created_at
    ON error_log (created_at DESC);

INSERT INTO icecream_flavor (name, is_available)
VALUES ('바닐라', TRUE), ('초콜릿', TRUE), ('딸기', TRUE)
ON CONFLICT (name) DO NOTHING;
