--
-- PostgreSQL database dump
--

\restrict EoQ1CFbGG2nHGcyDSeTQa8j5SkARi48IzPAfltNelPscdjCl9r1lTwAS20a9ZcV

-- Dumped from database version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: error_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.error_log (
    id integer NOT NULL,
    order_id integer NOT NULL,
    process_step character varying(50) NOT NULL,
    error_code character varying(50) NOT NULL,
    message character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT error_log_error_code_check CHECK (((error_code)::text = ANY ((ARRAY['GRIP_FAILED'::character varying, 'MOVE_FAILED'::character varying, 'SCOOP_FAILED'::character varying, 'UNKNOWN_ERROR'::character varying])::text[]))),
    CONSTRAINT error_log_process_step_check CHECK (((process_step)::text = ANY ((ARRAY['CUP_PICK'::character varying, 'CUP_PLACE'::character varying, 'SCOOP_PICK'::character varying, 'MOVE_TO_ICECREAM'::character varying, 'SCOOP_ICECREAM'::character varying, 'PUT_ICECREAM_IN_CUP'::character varying, 'SCOOP_RETURN'::character varying, 'SERVE_CUP'::character varying])::text[])))
);


--
-- Name: error_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.error_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.error_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: icecream_flavor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.icecream_flavor (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    is_available boolean DEFAULT true NOT NULL,
    name_en character varying(50) DEFAULT ''::character varying NOT NULL,
    description character varying(120) DEFAULT ''::character varying NOT NULL,
    description_en character varying(120) DEFAULT ''::character varying NOT NULL
);


--
-- Name: icecream_flavor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.icecream_flavor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.icecream_flavor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_history (
    id integer NOT NULL,
    flavor_id integer NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    ordered_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT order_history_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: order_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: robot_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.robot_state (
    id smallint NOT NULL,
    status character varying(20) NOT NULL,
    current_order_id integer,
    current_step character varying(50) DEFAULT ''::character varying NOT NULL,
    message character varying(255) DEFAULT ''::character varying NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT robot_state_id_check CHECK ((id = 1)),
    CONSTRAINT robot_state_status_check CHECK (((status)::text = ANY ((ARRAY['IDLE'::character varying, 'READY'::character varying, 'PROCESSING'::character varying, 'RETURNING_HOME'::character varying, 'ERROR'::character varying, 'STOPPED'::character varying])::text[])))
);


--
-- Data for Name: error_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.error_log (id, order_id, process_step, error_code, message, created_at) FROM stdin;
\.


--
-- Data for Name: icecream_flavor; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.icecream_flavor (id, name, is_available, name_en, description, description_en) FROM stdin;
1	바닐라	t	Vanilla	부드럽고 진한 기본 바닐라	Smooth and rich classic vanilla
2	초콜릿	t	Chocolate	초코칩이 씹히는 진한 초콜릿	Rich chocolate with crunchy chips
3	딸기	t	Strawberry	생딸기 과육이 들어간 상큼함	Fresh and fruity strawberry
4	민트초코	f	Mint Chocolate	상쾌한 민트와 초콜릿 칩	Refreshing mint with chocolate chips
5	쿠키앤크림	f	Cookies and Cream	바삭한 쿠키가 가득한 크림	Creamy ice cream packed with cookies
\.


--
-- Data for Name: order_history; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_history (id, flavor_id, status, ordered_at) FROM stdin;
\.


--
-- Data for Name: robot_state; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.robot_state (id, status, current_order_id, current_step, message, updated_at) FROM stdin;
1	IDLE	\N		다음 주문 대기	2026-08-26 21:43:18.047692+09
\.


--
-- Name: error_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.error_log_id_seq', 1, false);


--
-- Name: icecream_flavor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.icecream_flavor_id_seq', 10, true);


--
-- Name: order_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_history_id_seq', 1, false);


--
-- Name: error_log error_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.error_log
    ADD CONSTRAINT error_log_pkey PRIMARY KEY (id);


--
-- Name: icecream_flavor icecream_flavor_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.icecream_flavor
    ADD CONSTRAINT icecream_flavor_name_key UNIQUE (name);


--
-- Name: icecream_flavor icecream_flavor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.icecream_flavor
    ADD CONSTRAINT icecream_flavor_pkey PRIMARY KEY (id);


--
-- Name: order_history order_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_history
    ADD CONSTRAINT order_history_pkey PRIMARY KEY (id);


--
-- Name: robot_state robot_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robot_state
    ADD CONSTRAINT robot_state_pkey PRIMARY KEY (id);


--
-- Name: idx_error_log_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_error_log_created_at ON public.error_log USING btree (created_at DESC);


--
-- Name: idx_error_log_order_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_error_log_order_id ON public.error_log USING btree (order_id);


--
-- Name: idx_order_history_flavor_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_history_flavor_id ON public.order_history USING btree (flavor_id);


--
-- Name: idx_order_history_ordered_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_history_ordered_at ON public.order_history USING btree (ordered_at DESC);


--
-- Name: error_log error_log_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.error_log
    ADD CONSTRAINT error_log_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.order_history(id) ON DELETE CASCADE;


--
-- Name: order_history order_history_flavor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_history
    ADD CONSTRAINT order_history_flavor_id_fkey FOREIGN KEY (flavor_id) REFERENCES public.icecream_flavor(id);


--
-- Name: robot_state robot_state_current_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robot_state
    ADD CONSTRAINT robot_state_current_order_id_fkey FOREIGN KEY (current_order_id) REFERENCES public.order_history(id);


--
-- PostgreSQL database dump complete
--

\unrestrict EoQ1CFbGG2nHGcyDSeTQa8j5SkARi48IzPAfltNelPscdjCl9r1lTwAS20a9ZcV

