<?xml version="1.0"?>
<package format="3">
  <name>roskin_robot</name>
  <version>0.0.1</version>
  <description>Roskin Robbins Doosan M0609 automation stages 1 to 5</description>
  <maintainer email="student@example.com">roskin team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>dsr_common2</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
