CREATE TABLE IF NOT EXISTS admin_command (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command VARCHAR(30) NOT NULL CHECK (command IN (
        'START', 'PAUSE', 'END', 'HOME', 'CUP_PICK', 'CUP_PLACE',
        'SCOOP_PICK', 'ICECREAM', 'SERVE_CUP', 'GRIPPER_OPEN',
        'GRIPPER_CUP', 'GRIPPER_SCOOP', 'MOVE_JOINTS'
    )),
    joint_positions DOUBLE PRECISION[],
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (
        status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED')
    ),
    message VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_admin_command_status_created
    ON admin_command (status, created_at, id);
